language: php
php:
  - '5.6'
sudo: required
dist: trusty
group: edge

before_install:
  - uname -a
  - php --version
  - phpunit --version
  - composer self-update
install:
  - composer install
script:
  - vendor/bin/phpunit

notifications:
  email: true
