language: php
php: 5.6
sudo: required
dist: trusty
before_install:
  - uname -a
  - php --version
  - phpunit --version
  - composer self-update
install:
  - composer install
script:
    - head /proc/sys/fs/aio*
    - ps -jef --forest
notifications:
    email: never
